const compliments = [
        "You're amazing!",
        "You're beautiful inside and out!",
        "You're a ray of sunshine!",
        "You're incredibly smart!",
        "You have a heart of gold!",
        "You're one of a kind!",
        "You're a true inspiration!",
        "You make the world a better place!",
        "You're doing great things!",
        "You're loved and appreciated!",
        "You're wonderfully unique!",
        "You're a gem!",
        "You're so kind-hearted!",
        "You're a blessing to others!",
        "You're always there for me!",
        "You have a contagious smile!",
        "You're a great listener!",
        "You have a wonderful sense of humor!",
        "You're full of creativity!",
        "You're fearless and strong!",
        "You're incredibly talented!",
        "You're a beacon of hope!",
        "You're a joy to be around!",
        "You're thoughtful and caring!",
        "You have a heart of compassion!",
        "You're a fantastic friend!",
        "You have a positive outlook on life!",
        "You're truly remarkable!",
        "You're a source of happiness!",
        "You're so generous!",
        "You have an amazing spirit!",
        "You're always so supportive!",
        "You're absolutely stunning!",
        "You're a champion!",
        "You're full of determination!",
        "You're an inspiration to others!",
        "You're so talented and creative!",
        "You have a heart of gold!",
        "You're a true gem!",
        "You're so genuine!",
        "You're incredibly resilient!",
        "You're so strong and brave!",
        "You're a wonderful role model!",
        "You're a shining star!",
        "You're so graceful!",
        "You have a beautiful soul!",
        "You light up the room!",
        "You're so dependable!",
        "You have an incredible work ethic!",
        "You're always willing to help!",
        "You're a true team player!",
        "You're so intelligent!",
        "You have a heart of gold!",
        "You're so creative!",
        "You're a true original!",
        "You're absolutely stunning!",
        "You're a true treasure!",
        "You're so inspiring!",
        "You have a heart of gold!",
        "You're incredibly talented!",
        "You're so compassionate!",
        "You're always there for others!",
        "You're so resilient!",
        "You're a ray of sunshine!",
        "You have an amazing spirit!",
        "You're such a blessing!",
        "You're full of positive energy!",
        "You're a true joy!",
        "You're so kind-hearted!",
        "You have an amazing laugh!",
        "You're a breath of fresh air!",
        "You're so thoughtful!",
        "You have a beautiful smile!",
        "You're incredibly generous!",
        "You're so genuine!",
        "You have a heart of gold!",
        "You're an inspiration to others!",
        "You're incredibly brave!",
        "You're a true hero!",
        "You're so courageous!",
        "You're a fantastic listener!",
        "You're full of creativity!",
        "You're so talented!",
        "You're so intelligent!",
        "You have a heart of gold!",
        "You're incredibly caring!",
        "You're so supportive!",
        "You're such a wonderful friend!",
        "You're always there when I need you!",
        "You're so understanding!",
        "You're a true blessing!",
        "You're absolutely amazing!",
        "You're so full of life!",
        "You're so dependable!",
        "You're always so positive!",
        "You're so resilient!",
        "You're incredibly strong!",
        "You're so inspiring!",
        "You're a true champion!",
        "You're so talented and creative!",
        "You're so genuine!",
        "You're incredibly generous!",
        "You have a heart of gold!",
        "You're such a good-hearted person!",
        "You're always so kind!",
        "You're incredibly thoughtful!",
        "You're a true gem!",
        "You're so full of positivity!",
        "You're a ray of sunshine on a cloudy day!",
        "You're such a joy to be around!",
        "You're so warm and caring!",
        "You're always so genuine!",
        "You're incredibly resilient!",
        "You're so talented!",
        "You have such a beautiful heart!",
        "You're so inspiring!",
        "You're such a wonderful person!",
        "You're so incredibly brave!",
        "You have a heart of gold!",
        "You're always so supportive!",
        "You're so full of love and kindness!",
        "You're such a true friend!",
        "You're so incredibly strong!",
        "You're so thoughtful and caring!",
        "You're so full of positive energy!",
        "You're such a bright light in my life!",
        "You're absolutely amazing!",
        "You're such an inspiration!",
        "You're so full of joy and laughter!",
        "You're incredibly talented!",
        "You're always so generous!",
        "You're so genuine and authentic!",
        "You have such a beautiful soul!",
        "You're so full of wisdom and grace!",
        "You're such a blessing to everyone around you!",
        "You're so full of creativity and passion!",
        "You're so full of life and energy!",
        "You're always so compassionate and caring!",
        "You're such a wonderful listener!",
        "You're so supportive and encouraging!",
        "You're so full of love and kindness!",
        "You're so incredibly brave and courageous!",
        "You're always so positive and optimistic!",
        "You're such a shining example of goodness!",
        "You're so thoughtful and considerate!",
        "You're always so patient and understanding!",
        "You're so resilient and strong-willed!",
        "You're such an inspiration to everyone around you!",
        "You're so full of passion and determination!",
        "You're such a beacon of light and hope!",
        "You're so warm and welcoming to everyone you meet!",
        "You're always so humble and down-to-earth!",
        "You're so full of wisdom and insight!",
        "You're so incredibly talented and creative!",
        "You're such a force for good in the world!",
        "You're so full of love and kindness towards others!",
        "You're always so generous with your time and resources!",
        "You're so brave and courageous in the face of adversity!",
        "You're such a wonderful example of strength and resilience!",
        "You're always so positive and optimistic, even in tough times!",
        "You're such a joy to be around, always lifting others up!",
        "You're so incredibly talented and capable!",
        "You're such a wonderful friend and confidant!",
        "You're always so compassionate and caring towards others!",
        "You're so full of love and light, brightening everyone's day!",
        "You're such an inspiration to me and everyone who knows you!",
        "You're always so kind and considerate towards others!",
        "You're so full of positivity and hope for the future!",
        "You're such a beautiful soul, inside and out!",
        "You're always so selfless and giving!",
        "You're so full of grace and elegance!",
        "You're such a shining star, lighting up the world with your presence!",
        "You're always so loving and supportive, no matter what!",
        "You're so full of wisdom and insight, guiding others with your wisdom!",
        "You're such a bright spark, bringing joy wherever you go!",
        "You're always so generous with your time and energy!",
        "You're so full of life and enthusiasm!",
        "You're such a wonderful example of kindness and compassion!",
        "You're always so positive and uplifting to be around!",
        "You're so full of talent and creativity!",
        "You're such a true friend, always there when I need you!",
        "You're always so patient and understanding!",
        "You're so full of joy and laughter, brightening even the darkest days!",
        "You're such an incredible person, inside and out!",
        "You're always so genuine and authentic!",
        "You're so full of grace and beauty!",
        "You're such an amazing role model!",
        "You're always so loving and caring towards others!",
        "You're so full of wisdom and insight, always offering valuable advice!",
        "You're such a wonderful listener, always there to lend an ear!",
        "You're always so positive and optimistic, even in challenging times!",
        "You're so full of kindness and compassion!",
        "You're such a beacon of light and hope to those around you!",
        "You're always so generous and giving, never hesitating to help others!",
        "You're so full of energy and enthusiasm!",
        "You're such a joy to be around, always spreading happiness wherever you go!",
        "You're always so humble and down-to-earth, despite your many talents!",
        "You're so full of love and warmth, making everyone feel welcome and valued!",
        "You're such a bright and shining star in my life!",
        "You're always so supportive and encouraging, cheering me on every step of the way!",
        "You're so full of courage and determination!",
        "You're such a wonderful example of strength and resilience, inspiring others with your bravery!",
        "You're always so positive and hopeful, seeing the best in every situation!",
        "You're so full of love and kindness, touching the hearts of everyone you meet!",
        "You're such a beautiful soul, radiating love and light wherever you go!",
        "You're always so giving and generous, putting others' needs before your own!",
        "You're so full of wisdom and insight, guiding others with your knowledge and experience!",
        "You're such a joy to be around, bringing laughter and happiness into every moment!",
        "You're always so selfless and caring, always thinking of others before yourself!",
        "You're so full of compassion and empathy, understanding the struggles of those around you!",
        "You're such a beacon of hope and inspiration to those who know you!",
        "You're always so positive and uplifting, lifting the spirits of those around you!",
        "You're so full of creativity and innovation, always coming up with new ideas and solutions!",
        "You're such a wonderful friend and companion, always there to lend a helping hand!",
        "You're always so patient and understanding, willing to listen and offer support whenever it's needed!",
        "You're so full of joy and laughter, bringing smiles to the faces of everyone you meet!",
        "You're such an incredible person, with so much to offer the world!",
        "You're always so genuine and authentic, never afraid to be yourself!",
        "You're so full of grace and elegance, carrying yourself with poise and dignity!",
        "You're such an amazing role model, inspiring others with your actions and words!",
        "You're always so loving and compassionate, caring deeply for those around you!",
        "You're so full of wisdom and insight, always offering valuable advice and guidance!",
        "You're such a wonderful listener, always willing to lend an ear and offer support!",
        "You're always so positive and optimistic, seeing the good in every situation!",
        "You're so full of kindness and generosity, always giving your time and energy to help others!",
        "You're such a beacon of light and hope, shining brightly even in the darkest of times!",
        "You're always so humble and down-to-earth, never letting your success go to your head!",
        "You're so full of love and warmth, making everyone around you feel loved and appreciated!",
        "You're such a bright and shining star, illuminating the lives of those around you!",
        "You're always so supportive and encouraging, cheering me on through every challenge and triumph!",
        "You're so full of courage and determination, never giving up on your dreams and aspirations!",
        "You're such a wonderful example of strength and resilience, overcoming obstacles with grace and fortitude!",
        "You're always so positive and hopeful, seeing the beauty and potential in every moment!",
        "You're so full of love and kindness, spreading joy and happiness wherever you go!",
        "You're such a beautiful soul, with a heart as pure and radiant as the sun!",
        "You're always so giving and generous, sharing your time and talents with those in need!",
        "You're so full of wisdom and insight, offering valuable advice and guidance to those who seek it!",
        "You're such a joy to be around, bringing laughter and light into the lives of everyone you meet!",
        "You're always so selfless and caring, putting the needs of others before your own!",
        "You're so full of compassion and empathy, understanding the struggles and sorrows of those around you!",
        "You're such a beacon of hope and inspiration, lighting the way for others with your strength and courage!",
        "You're always so positive and uplifting, lifting the spirits of those around you with your infectious energy!",
        "You're so full of creativity and imagination, always finding new ways to express yourself and inspire others!",
        "You're such a wonderful friend and companion, always there to lend a listening ear and a helping hand!",
        "You're always so patient and understanding, offering comfort and support to those who need it most!",
        "You're so full of joy and laughter, bringing smiles to the faces of everyone you meet!",
        "You're such an incredible person, with so much love and light to share with the world!",
        "You're always so genuine and authentic, never afraid to show your true self to the world!",
        "You're so full of grace and elegance, carrying yourself with dignity and poise wherever you go!",
        "You're such an amazing role model, inspiring others with your kindness and compassion!",
        "You're always so loving and caring, always there to offer a helping hand or a comforting hug!",
        "You're so full of wisdom and insight, offering valuable advice and guidance to those who need it most!",
        "You're such a wonderful listener, always willing to lend an ear and offer support to those in need!",
        "You're always so positive and optimistic, seeing the good in every situation and never losing hope!",
        "You're so full of kindness and generosity, always going above and beyond to help those around you!",
        "You're such a beacon of light and hope, shining brightly even in the darkest of times!",
        "You're always so humble and down-to-earth, never letting your success go to your head!",
        "You're so full of love and warmth, making everyone around you feel welcomed and appreciated!",
        "You're such a bright and shining star, illuminating the lives of those around you with your presence!",
        "You're always so supportive and encouraging, cheering me on through every challenge and triumph!",
        "You're so full of courage and determination, never giving up on your dreams and always striving for greatness!",
        "You're such a wonderful example of strength and resilience, overcoming obstacles with grace and fortitude!",
        "You're always so positive and hopeful, seeing the beauty and potential in every moment!",
        "You're so full of love and kindness, spreading joy and happiness wherever you go!",
        "You're such a beautiful soul, with a heart as pure and radiant as the sun!",
        "You're always so giving and generous, sharing your time and talents with those in need!",
        "You're so full of wisdom and insight, offering valuable advice and guidance to those who seek it!",
        "You're such a joy to be around, bringing laughter and light into the lives of everyone you meet!",
        "You're always so selfless and caring, putting the needs of others before your own!",
        "You're so full of compassion and empathy, understanding the struggles and sorrows of those around you!",
        "You're such a beacon of hope and inspiration, lighting the way for others with your strength and courage!",
        "You're always so positive and uplifting, lifting the spirits of those around you with your infectious energy!",
        "You're so full of creativity and imagination, always finding new ways to express yourself and inspire others!",
        "You're such a wonderful friend and companion, always there to lend a listening ear and a helping hand!",
        "You're always so patient and understanding, offering comfort and support to those who need it most!",
        "You're so full of joy and laughter, bringing smiles to the faces of everyone you meet!",
        "You're such an incredible person, with so much love and light to share with the world!",
        "You're always so genuine and authentic, never afraid to show your true self to the world!",
        "You're so full of grace and elegance, carrying yourself with dignity and poise wherever you go!",
        "You're such an amazing role model, inspiring others with your kindness and compassion!",
        "You're always so loving and caring, always there to offer a helping hand or a comforting hug!",
        "You're so full of wisdom and insight, offering valuable advice and guidance to those who need it most!",
        "You're such a wonderful listener, always willing to lend an ear and offer support to those in need!",
        "You're always so positive and optimistic, seeing the good in every situation and never losing hope!",
        "You're so full of kindness and generosity, always going above and beyond to help those around you!",
        "You're such a beacon of light and hope, shining brightly even in the darkest of times!",
        "You're always so humble and down-to-earth, never letting your success go to your head!",
        "You're so full of love and warmth, making everyone around you feel welcomed and appreciated!",
        "You're such a bright and shining star, illuminating the lives of those around you with your presence!",
        "You're always so supportive and encouraging, cheering me on through every challenge and triumph!",
        "You're so full of courage and determination, never giving up on your dreams and always striving for greatness!",
        "You're such a wonderful example of strength and resilience, overcoming obstacles with grace and fortitude!",
        "You're always so positive and hopeful, seeing the beauty and potential in every moment!",
        "You're so full of love and kindness, spreading joy and happiness wherever you go!",
        "You're such a beautiful soul, with a heart as pure and radiant as the sun!",
        "You're always so giving and generous, sharing your time and talents with those in need!",
        "You're so full of wisdom and insight, offering valuable advice and guidance to those who seek it!",
        "You're such a joy to be around, bringing laughter and light into the lives of everyone you meet!",
        "You're always so selfless and caring, putting the needs of others before your own!",
        "You're so full of compassion and empathy, understanding the struggles and sorrows of those around you!",
        "You're such a beacon of hope and inspiration, lighting the way for others with your strength and courage!",
        "You're always so positive and uplifting, lifting the spirits of those around you with your infectious energy!",
        "You're so full of creativity and imagination, always finding new ways to express yourself and inspire others!",
        "You're such a wonderful friend and companion, always there to lend a listening ear and a helping hand!",
        "You're always so patient and understanding, offering comfort and support to those who need it most!",
        "You're so full of joy and laughter, bringing smiles to the faces of everyone you meet!",
        "You're such an incredible person, with so much love and light to share with the world!",
        "You're always so genuine and authentic, never afraid to show your true self to the world!",
        "You're so full of grace and elegance, carrying yourself with dignity and poise wherever you go!",
        "You're such an amazing role model, inspiring others with your kindness and compassion!",
        "You're always so loving and caring, always there to offer a helping hand or a comforting hug!",
        "You're so full of wisdom and insight, offering valuable advice and guidance to those who need it most!",
        "You're such a wonderful listener, always willing to lend an ear and offer support to those in need!",
        "You're always so positive and optimistic, seeing the good in every situation and never losing hope!",
        "You're so full of kindness and generosity, always going above and beyond to help those around you!",
        "You're such a beacon of light and hope, shining brightly even in the darkest of times!",
        "You're always so humble and down-to-earth, never letting your success go to your head!",
        "You're so full of love and warmth, making everyone around you feel welcomed and appreciated!",
        "You're such a bright and shining star, illuminating the lives of those around you with your presence!",
        "You're always so supportive and encouraging, cheering me on through every challenge and triumph!",
        "You're so full of courage and determination, never giving up on your dreams and always striving for greatness!",
        "You're such a wonderful example of strength and resilience, overcoming obstacles with grace and fortitude!",
        "You're always so positive and hopeful, seeing the beauty and potential in every moment!",
        "You're so full of love and kindness, spreading joy and happiness wherever you go!",
        "You're such a beautiful soul, with a heart as pure and radiant as the sun!",
        "You're always so giving and generous, sharing your time and talents with those in need!",
        "You're so full of wisdom and insight, offering valuable advice and guidance to those who seek it!",
        "You're such a joy to be around, bringing laughter and light into the lives of everyone you meet!",
        "You're always so selfless and caring, putting the needs of others before your own!",
        "You're so full of compassion and empathy, understanding the struggles and sorrows of those around you!",
        "You're such a beacon of hope and inspiration, lighting the way for others with your strength and courage!",
        "You're always so positive and uplifting, lifting the spirits of those around you with your infectious energy!",
        "You're so full of creativity and imagination, always finding new ways to express yourself and inspire others!",
        "You're such a wonderful friend and companion, always there to lend a listening ear and a helping hand!",
        "You're always so patient and understanding, offering comfort and support to those who need it most!",
        "You're so full of joy and laughter, bringing smiles to the faces of everyone you meet!",
        "You're such an incredible person, with so much love and light to share with the world!",
        "You're always so genuine and authentic, never afraid to show your true self to the world!",
        "You're so full of grace and elegance, carrying yourself with dignity and poise wherever you go!",
        "You're such an amazing role model, inspiring others with your kindness and compassion!",
        "You're always so loving and caring, always there to offer a helping hand or a comforting hug!",
        "You're so full of wisdom and insight, offering valuable advice and guidance to those who need it most!",
        "You're such a wonderful listener, always willing to lend an ear and offer support to those in need!",
        "You're always so positive and optimistic, seeing the good in every situation and never losing hope!",
        "You're so full of kindness and generosity, always going above and beyond to help those around you!",
        "You're such a beacon of light and hope, shining brightly even in the darkest of times!",
        "You're always so humble and down-to-earth, never letting your success go to your head!",
        "You're so full of love and warmth, making everyone around you feel welcomed and appreciated!",
        "You're such a bright and shining star, illuminating the lives of those around you with your presence!",
        "You're always so supportive and encouraging, cheering me on through every challenge and triumph!",
        "You're so full of courage and determination, never giving up on your dreams and always striving for greatness!",
        "You're such a wonderful example of strength and resilience, overcoming obstacles with grace and fortitude!",
        "You're always so positive and hopeful, seeing the beauty and potential in every moment!",
        "You're so full of love and kindness, spreading joy and happiness wherever you go!",
        "You're such a beautiful soul, with a heart as pure and radiant as the sun!",
        "You're always so giving and generous, sharing your time and talents with those in need!",
        "You're so full of wisdom and insight, offering valuable advice and guidance to those who seek it!",
        "You're such a joy to be around, bringing laughter and light into the lives of everyone you meet!",
        "You're always so selfless",
      
  ];
  
  const generateBtn = document.getElementById('generate-btn');
  const complimentElement = document.getElementById('compliment');
  
  generateBtn.addEventListener('click', () => {
      const randomIndex = Math.floor(Math.random() * compliments.length);
      const randomCompliment = compliments[randomIndex];
      complimentElement.textContent = randomCompliment;
  });
  